### ISSUE TITLE
[Suggestion] FAQ Categories

### ISSUE THREAD

**Issue by H4nSolo** [Azuriom/Plugin-FAQ#1]
Is that Possible to add Categories?

> Example:
> 
> - SITE FAQ
>     Q: Why i cant see anything?
>     A: Diable you Adblocker^^
> 
>     Q: Blabla blub...
>     A: Blub?
> 
> - SERVER FAQ
>     Q: Can i use Mods?
>     A: Yes you can use Forge Modloader to load any Mods...
> 
>     Q: Why banned?
>     A: You break the rules...

**Comment by MrMicky-FR** [comment]
Hello, unfortunately we don't plan to add this feature anymore. If you need more control the Wiki plugin may be more suitable 😃
