### ISSUE TITLE
[Suggestion]Support for HTML or Markdown formatted text

### ISSUE THREAD

**Issue by H4nSolo** [Azuriom/Plugin-FAQ#2]
Allow support of markdown or HTML formatted text

**Comment by Alemiz112** [comment]
Any progress?

**Comment by MrMicky-FR** [comment]
We added a markdown API in the last release of Azuriom, we will add it in the FAQ in one week when most websites has updated to prevent issues

**Comment by Alemiz112** [comment]
Great. Thanks!

**Comment by MrMicky-FR** [comment]
Added in https://github.com/Azuriom/Plugin-FAQ/commit/31e77416c572afc30d48610e43ba03b6014e48c1, you can update to the last version of the plugin to use it (also make sure to update Azuriom before).
