### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by x9nico** [Azuriom/Plugin-FAQ#4]
Bonjour ou Bonsoir,

J'aime bien votre système de FAQ ! Bravo !

Cependant, je trouve ça dommage que nous ne pouvons pas insérer des images dans les réponses.
Ca aurait été cool je pense d'ajouter ça 👍

**Comment by MrMicky-FR** [comment]
Bonjour, les réponses supportent le [format Markdown](https://guides.github.com/features/mastering-markdown/) donc il est possible d'ajouter des images et de la mise en forme, après effectivement ajouter un éditeur avec le support du glisser-déposer serait plus pratique
